config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, shallow: true

  namespace :admin, path: 'blabla666' do
    resources :products, shallow:true do 

    end

    resources :users, shallow:true do 
      member do 
        get 'user_product', to: 'users#products_show'        
      end
    end

    # resources :admins, shallow:true do 
    #   collection do 
    #     get 'user', to: 'admins#user'
    #     get 'product', to: 'admins#product'  
    #     get 'index', to: 'admins#index'
        
    #     get 'user_new', to: 'admins#user_new'
    #     post 'user_create', to: 'admins#user_create'

    #     get 'product_new', to: 'admins#product_new'
    #     post 'product_create', to: 'admins#product_create'
    #   end

    #   member do 
    #     delete 'user_destroy', to: 'admins#user_destroy'
    #     get 'user_edit', to: 'admins#user_edit'
    #     put 'user_update', to: 'admins#user_update'

    #     get 'user_product', to: 'admins#user_products_show'
        
    #     delete 'product_destroy', to: 'admins#product_destroy'
    #     get 'product_edit', to: 'admins#product_edit'
    #     put 'product_update', to: 'admins#product_update'
    #   end
    # end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'log_out', to: 'sessions#destroy'
  get 'user_show', to: 'sessions#show'
  put 'session_update', to: 'sessions#update'
  get 'delet_confirm', to: 'sessions#delete_confirm'
  delete 'delete', to: 'sessions#delete_account'
end

app/views/admin/admins/product.html.erb
<p>Product</p>

<div class="d-flex flex-row">
  <%= render "shared/admins/sidebar" %>
  <div>
    <% if flash[:notice] or flash[:alert] %>
      <p class='alert alert-primary flash'>
        <%= flash[:notice] %>  <%= flash[:alert] %>
      </p> 
    <% end %>
    <table class="table table-striped table-hove">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Stock</th>
          <th scope="col">Create At</th>
          <th scope="col">Update At</th>
          <th scope="col">Scheduled Start</th>
          <th scope="col">Scheduled End</th>
          <th scope="col">Resolve</th>
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row"><%= product.id %></th>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.stock %></td>
            <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_start.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_end.strftime("%m/%d/%Y") %></td>
            <td><%= product.product_resolve %></td>
            <td><%= link_to "Delete", product_destroy_admin_admin_path(product), method:'Delete', data: {confirm: "Are you sure you want to delete this product?" } %></td>
            <td><%= link_to "Edit", product_edit_admin_admin_path(product) %></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/admins/product_edit.html.erb
<p>Product Edit Page </p>

<p><%= flash[:schedule_notice] %></p>
<div class="container">
  <%= form_with model: @product, url: product_update_admin_admin_path(@product), method: 'put' do |form|%>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :name, t('zh-TW.products.index.attributes.product.name'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :name, class: "form-control"%>
      </div>
      <div class="">
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :price, t('zh-TW.products.index.attributes.product.price'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :price, class: "form-control" %>
      </div>
      <div class="">
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :stock, t('zh-TW.products.index.attributes.product.stock'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :stock, class: "form-control" %>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :scheduled_start, t('zh-TW.products.index.attributes.product.scheduled_start'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-12">
        <%= form.datetime_local_field :scheduled_start, :value => @product.scheduled_start.nil? ? "" : @product.scheduled_start.strftime("%Y-%m-%dT%H:%M:%S"), class: "form-control" %>

        <i class="fa fa-calendar"></i>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :scheduled_end, t('zh-TW.products.index.attributes.product.scheduled_end'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-12">
        <input type="datetime-local" id="product_scheduled_end" name="product[scheduled_end]" class="datetimepicker_end form-control" value=<%= @product.scheduled_end.nil? ? '' : @product.scheduled_end.strftime("%Y-%m-%dT%H:%M:%S")%> >
        <i class="fa fa-calendar"></i>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :product_resolve, t('zh-TW.products.index.attributes.product.product_resolve'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-10">
        <select name="product[product_resolve]" id="product_product_resolve" class="form-select form-select-sm mb-3" >
          <option selected="selected" value="不需叫貨">不需叫貨</option>
          <option value="已叫貨">已叫貨</option>
          <option value="需叫貨">需叫貨</option>
        </select>
      </div>
    </div>
    <div class="submit">
      <%= form.submit(class: "btn btn-primary mr-2")%>
    </div>
  <% end %>
</div>

app/views/admin/admins/product_new.html.erb
<p>Product Edit Page </p>

<p><%= flash[:schedule_notice] %></p>
<div class="container">
  <%= form_with model: @product, url: product_create_admin_admins_path(user_id: params[:user_id]), method: 'post' do |form|%>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :name, t('zh-TW.products.index.attributes.product.name'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :name, class: "form-control"%>
      </div>
      <div class="">
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :price, t('zh-TW.products.index.attributes.product.price'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :price, class: "form-control" %>
      </div>
      <div class="">
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :stock, t('zh-TW.products.index.attributes.product.stock'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field">
        <%= form.text_field :stock, class: "form-control" %>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :scheduled_start, t('zh-TW.products.index.attributes.product.scheduled_start'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-12">
        <%= form.datetime_local_field :scheduled_start, :value => @product.scheduled_start.nil? ? "" : @product.scheduled_start.strftime("%Y-%m-%dT%H:%M:%S"), class: "form-control" %>

        <i class="fa fa-calendar"></i>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :scheduled_end, t('zh-TW.products.index.attributes.product.scheduled_end'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-12">
        <input type="datetime-local" id="product_scheduled_end" name="product[scheduled_end]" class="datetimepicker_end form-control" value=<%= @product.scheduled_end.nil? ? '' : @product.scheduled_end.strftime("%Y-%m-%dT%H:%M:%S")%> >
        <i class="fa fa-calendar"></i>
      </div>
    </div>
    <div class="input mb-3 row">
      <div class="label">
        <%= form.label :product_resolve, t('zh-TW.products.index.attributes.product.product_resolve'), class: "col-sm-2 col-form-label"%>
      </div>
      <div class="field col-sm-10">
        <select name="product[product_resolve]" id="product_product_resolve" class="form-select form-select-sm mb-3" >
          <option selected="selected" value="不需叫貨">不需叫貨</option>
          <option value="已叫貨">已叫貨</option>
          <option value="需叫貨">需叫貨</option>
        </select>
      </div>
    </div>
    <div class="submit">
      <%= form.submit(class: "btn btn-primary mr-2")%>
    </div>
  <% end %>
</div>

app/views/admin/admins/user.html.erb
<p>User</p>
<% if flash[:notice] or flash[:alert] %>
  <p class='alert alert-primary flash'><%= flash[:notice] %>  <%= flash[:alert] %>
  </p> 
<% end %>

<div class="d-flex flex-row">
  <%= render "shared/admins/sidebar" %>
  <div>
    <div class="d-flex">
      <div class=" my-4">
        <%= link_to t('.actions.new'), user_new_admin_admins_path, class: "btn btn-primary mr-2" %>
      </div>  
    </div>
    <table class="table table-striped table-hove">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Password</th>
          <th scope="col">Admin</th>
          <th scope="col">Num of Products</th>
          <th scope="col">Create At</th>
          <th scope="col">Update At</th>
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= link_to user.name, user_product_admin_admin_path(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.password %></td>
            <td><%= user.admin %></td>
            <td><%= user.products.count %></td>
            <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= user.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= link_to "Delete", user_destroy_admin_admin_path(user), method:'Delete', data: {confirm: "Are you sure you want to delete this user?" } %></td>
            <td><%= link_to "Edit", user_edit_admin_admin_path(user) %></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/admins/user_edit.html.erb
<div class="d-flex justify-content-between">
  <div>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5zM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5z"/>
    </svg>
    <%= link_to 'Previous Page', user_admin_admins_path %>    
  </div>
  <p>Edit User Page</p>
  <div></div>
</div>
<% if flash[:notice] or flash[:alert] %>
  <p class='alert alert-warning flash'>
    <%= flash[:notice] %>  <%= flash[:alert] %>
  </p> 
<% end %>
<%= form_with model: @user, url: user_update_admin_admin_path(@user), method: 'put' do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name'%>
    <%= form.label :name , 'Name'%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :email, class: 'form-control', placeholder: 'name@example.com' %>
    <%= form.label :email , 'Email address'%>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password, class: 'form-control', placeholder: 'Password'%>
    <%= form.label :password , 'Password'%>
  </div>
  <div class="form-floating mb-3">
    <select name="user[admin]" id="user_admin" class="form-select form-select-sm mb-3" aria-label="false" >
      <option selected="selected" value="false">false</option>
      <option value="true">true</option>
    </select>
  </div>
  <div class="form-floating">
    <%= form.submit(class: "btn btn-primary my-5", value: 'Update User')%>
  </div>
<% end %>

app/views/admin/admins/user_new.html.erb
<p> Create New User </p>
<%= form_with model: @user, url: user_create_admin_admins_path do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name'%>
    <%= form.label :name , 'Name'%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :email, class: 'form-control', placeholder: 'name@example.com' %>
    <%= form.label :email , 'Email address'%>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password, class: 'form-control', placeholder: 'Password'%>
    <%= form.label :password , 'Password'%>
  </div>
  <div class="form-floating mb-3">
    <select name="user[admin]" id="user_admin" class="form-select form-select-sm mb-3"  >
      <option selected="selected" value="False">False</option>
      <option value="True">True</option>
    </select>
  </div>
  <div class="form-floating">
    <%= form.submit(class: "btn btn-primary my-5", value: 'Create User')%>
  </div>
<% end %>

app/views/admin/admins/user_products_show.html.erb
<p>Product</p>

<div class="d-flex flex-row">
  <%= render "shared/admins/sidebar" %>
  <div>
    <div class="d-flex">
      <div class=" my-4">
        <%= link_to t('.actions.new'), product_new_admin_admins_path(user_id: @user.id), class: "btn btn-primary mr-2" %>
      </div>  
    </div>
    <% if flash[:notice] or flash[:alert] %>
      <p class='alert alert-primary flash'>
        <%= flash[:notice] %>  <%= flash[:alert] %>
      </p> 
    <% end %>

    <div class="card">
      <h5 class="card-header">
        <%= @user.name %>
      </h5>  
    </div>
    <table class="table table-striped table-hove">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Stock</th>
          <th scope="col">Create At</th>
          <th scope="col">Update At</th>
          <th scope="col">Scheduled Start</th>
          <th scope="col">Scheduled End</th>
          <th scope="col">Resolve</th>
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row"><%= product.id %></th>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.stock %></td>
            <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_start.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_end.strftime("%m/%d/%Y") %></td>
            <td><%= product.product_resolve %></td>
            <td><%= link_to "Delete", product_destroy_admin_admin_path(product), method:'Delete', data: {confirm: "Are you sure you want to delete this product?" } %></td>
            <td><%= link_to "Edit", product_edit_admin_admin_path(product) %></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>