config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, shallow: true

  namespace :admin, path: 'blabla666' do
    resources :products, shallow:true do 

    end

    resources :users, shallow:true do 
      member do 
        get 'user_product', to: 'users#products_show'        
      end
    end

    # resources :admins, shallow:true do 
    #   collection do 
    #     get 'user', to: 'admins#user'
    #     get 'product', to: 'admins#product'  
    #     get 'index', to: 'admins#index'
        
    #     get 'user_new', to: 'admins#user_new'
    #     post 'user_create', to: 'admins#user_create'

    #     get 'product_new', to: 'admins#product_new'
    #     post 'product_create', to: 'admins#product_create'
    #   end

    #   member do 
    #     delete 'user_destroy', to: 'admins#user_destroy'
    #     get 'user_edit', to: 'admins#user_edit'
    #     put 'user_update', to: 'admins#user_update'

    #     get 'user_product', to: 'admins#user_products_show'
        
    #     delete 'product_destroy', to: 'admins#product_destroy'
    #     get 'product_edit', to: 'admins#product_edit'
    #     put 'product_update', to: 'admins#product_update'
    #   end
    # end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'log_out', to: 'sessions#destroy'
  get 'user_show', to: 'sessions#show'
  put 'session_update', to: 'sessions#update'
  get 'delet_confirm', to: 'sessions#delete_confirm'
  delete 'delete', to: 'sessions#delete_account'
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password, presence: true

  has_many :products, :dependent => :destroy
  
  before_destroy :check_last_admin?
  before_create :encrypt_password

  def self.log_in(params)
    pwd = params[:password]
    pwd = Digest::SHA1.hexdigest("a#{pwd}z")
    User.find_by(email: params[:email], password: pwd)
  end

  private

  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end

  def check_last_admin?
    if User.pluck(:admin).count(true) == 1
      errors[:Check] << "It is last admin. Can not delete or edit it!"
      throw :abort 
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.includes(:products)
    authorize @users, :admin_user?
  end 

  def new
    @user = User.new
  end  

  def create
    @user = User.new(registration_params)

    respond_to do |format|
      if @user.save
        format.html {
          flash[:alert] = 'Successfully Add New User'
          redirect_to admin_users_path
        }
      else
        format.html {
          flash[:alert] = 'Something wrong'
          render :new
        }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:notice] = 'Successfully Delete Account'
    else 
      flash[:notice] = @user.errors.full_messages
    end
    redirect_to admin_users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(
          {
            :admin => params[:user][:admin],
            :name => params[:user][:name],
            :email => params[:user][:email],
            :password => Digest::SHA1.hexdigest("a#{params[:user][:password]}z")
          }
        )
        format.html {
          redirect_to admin_users_path
        }
      else
        format.html {
          render :edit
        }
      end
    end
  end

  def products_show
    @user = User.find(params[:id])
    if params[:tag]
      @products = Tag.find_by!(name: params[:tag]).products.where(user_id: params[:id])
    else
      @products = Product.where(user_id: params[:id]).includes(:tags)
    end
  end

  
  private

  def registration_params
    params.require(:user).permit(:email, :password, :name, :admin)
  end
end

app/helpers/user_helper.rb
module UserHelper 
  def user_sign_in?
    if current_user
      return true
    else
      return false
    end
  end

  def current_user
    if session[:userkey].present?
      @user ||= User.find_by(id: session[:userkey])
    else
      nil
    end
  end
end

app/views/admin/users/edit.html.erb
<div class="d-flex justify-content-between">
  <div>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5zM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5z"/>
    </svg>
    <%= link_to 'Previous Page', admin_users_path %>    
  </div>
  <p>Edit User Page</p>
  <div></div>
</div>
<% if flash[:notice] or flash[:alert] %>
  <p class='alert alert-warning flash'>
    <%= flash[:notice] %>  <%= flash[:alert] %>
  </p> 
<% end %>
<%= form_with model: @user, url: admin_user_path(@user), method: 'put' do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name'%>
    <%= form.label :name , 'Name'%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :email, class: 'form-control', placeholder: 'name@example.com' %>
    <%= form.label :email , 'Email address'%>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password, class: 'form-control', placeholder: 'Password'%>
    <%= form.label :password , 'Password'%>
  </div>
  <div class="form-floating mb-3">
    <select name="user[admin]" id="user_admin" class="form-select form-select-sm mb-3" aria-label="false" >
      <option selected="selected" value="false">false</option>
      <option value="true">true</option>
    </select>
  </div>
  <div class="form-floating">
    <%= form.submit(class: "btn btn-primary my-5", value: 'Update User')%>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<p>User</p>
<% if flash[:notice] or flash[:alert] %>
  <p class='alert alert-primary flash'><%= flash[:notice] %>  <%= flash[:alert] %>
  </p> 
<% end %>

<div class="d-flex flex-row">
  <%= render "shared/admins/sidebar" %>
  <div>
    <div class="d-flex">
      <div class=" my-4">
        <%= link_to t('.actions.new'), new_admin_user_path, class: "btn btn-primary mr-2" %>
      </div>  
    </div>
    <table class="table table-striped table-hove">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Password</th>
          <th scope="col">Admin</th>
          <th scope="col">Num of Products</th>
          <th scope="col">Create At</th>
          <th scope="col">Update At</th>
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= link_to user.name, user_product_admin_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td><%= user.password %></td>
            <td><%= user.admin %></td>
            <td><%= user.products.count %></td>
            <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= user.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= link_to "Delete", admin_user_path(user), method:'Delete', data: {confirm: "Are you sure you want to delete this user?" } %></td>
            <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<p> Create New User </p>
<%= form_with model: @user, url: admin_users_path, method: 'post' do |form| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <% @user.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name'%>
    <%= form.label :name , 'Name'%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :email, class: 'form-control', placeholder: 'name@example.com' %>
    <%= form.label :email , 'Email address'%>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password, class: 'form-control', placeholder: 'Password'%>
    <%= form.label :password , 'Password'%>
  </div>
  <div class="form-floating mb-3">
    <select name="user[admin]" id="user_admin" class="form-select form-select-sm mb-3"  >
      <option selected="selected" value="False">False</option>
      <option value="True">True</option>
    </select>
  </div>
  <div class="form-floating">
    <%= form.submit(class: "btn btn-primary my-5", value: 'Create User')%>
  </div>
<% end %>

app/views/admin/users/products_show.html.erb
<p>Product</p>

<div class="d-flex flex-row">
  <%= render "shared/admins/sidebar" %>
  <div>
    <div class="d-flex">
      <div class=" my-4">
        <%= link_to t('.actions.new'), new_admin_product_path(user_id: @user.id), class: "btn btn-primary mr-2" %>
      </div>  
    </div>
    <% if flash[:notice] or flash[:alert] %>
      <p class='alert alert-primary flash'>
        <%= flash[:notice] %>  <%= flash[:alert] %>
      </p> 
    <% end %>

    <div class="card">
      <h5 class="card-header">
        <%= link_to @user.name, user_product_admin_user_path(@user.id),class: "text-decoration-none" %>
      </h5>  
    </div>
    <table class="table table-striped table-hove">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Stock</th>
          <th scope="col">Tags</th>
          <th scope="col">Create At</th>
          <th scope="col">Update At</th>
          <th scope="col">Scheduled Start</th>
          <th scope="col">Scheduled End</th>
          <th scope="col">Resolve</th>
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <th scope="row"><%= product.id %></th>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.stock %></td>
            <td><%= product.tags.map{|tag| link_to tag.name, user_product_admin_user_path(@user.id, tag: tag.name), class: "btn btn-secondary btn-sm"}.join(' ').html_safe %></td>
            <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_start.strftime("%m/%d/%Y") %></td>
            <td><%= product.scheduled_end.strftime("%m/%d/%Y") %></td>
            <td><%= product.product_resolve %></td>
            <td><%= link_to "Delete", admin_product_path(product), method:'Delete', data: {confirm: "Are you sure you want to delete this product?" } %></td>
            <td><%= link_to "Edit", edit_admin_product_path(product) %></td>
          </tr>    
        <% end %>
      </tbody>
    </table>
  </div>
</div>